version: '3'

services:
  api:
    container_name: clean_node_api
    build: .
    command: "npm run dev"
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/api
      - ./dist:/home/node/api/dist
    restart: always
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: clean_node_api_mongo
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_URL=clean-node-api
    restart: always